# Generated by Django 4.0.5 on 2022-06-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlesheet', '0003_rename_order_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
