# Generated by Django 4.0.5 on 2022-06-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesheet', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='стоимость,$'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priceConvert',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='стоимость,₽'),
        ),
    ]
