# Generated by Django 4.0.5 on 2022-06-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesheet', '0007_alter_order_price_alter_order_priceconvert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.TextField(verbose_name='срок поставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priceConvert',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, verbose_name='стоимость в руб.'),
        ),
    ]
