# Generated by Django 4.0.5 on 2022-06-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesheet', '0009_alter_order_priceconvert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(verbose_name='стоимость,$'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priceConvert',
            field=models.FloatField(default=1.0, verbose_name='стоимость в руб.'),
        ),
    ]
