# Generated by Django 4.0.5 on 2022-06-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesheet', '0010_alter_order_price_alter_order_priceconvert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=128, verbose_name='стоимость,$'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priceConvert',
            field=models.CharField(max_length=128, verbose_name='стоимость в руб.'),
        ),
    ]
