# Generated by Django 4.0.5 on 2022-06-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesheet', '0011_alter_order_price_alter_order_priceconvert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.CharField(max_length=128, verbose_name='срок поставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=128, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(max_length=128, verbose_name='заказ №'),
        ),
    ]
