# Generated by Django 4.0.5 on 2022-06-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesheet', '0013_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.CharField(max_length=10, verbose_name='срок поставки'),
        ),
    ]
